name = "book-shop"
type = "javascript"

compatibility_date = "2024-04-04"

[build]
command = "npm run build"

[env.production]
workers_dev = false
routes = ["https://tu-dominio.pages.dev/*"]

[site]
entry-point = "."
functions = "./dist"  # Este es el directorio donde Astro genera las funciones de Cloudflare